CREATE DATABASE TESTE_ESTAGIO;
USE TESTE_ESTAGIO;

-- Criação da tabela OPERADORAS
CREATE TABLE OPERADORAS_ATIVAS (
    REGISTRO_ANS BIGINT(6) NOT NULL PRIMARY KEY,
    CNPJ CHAR(14) NOT NULL,
    RAZAO_SOCIAL VARCHAR(180) NOT NULL,
    NOME_FANTASIA VARCHAR(140),
    MODALIDADE VARCHAR(50),
    LOGRADOURO VARCHAR(80),
    NUMERO VARCHAR(20),
    COMPLEMENTO VARCHAR(80),
    BAIRRO VARCHAR(60),
    CIDADE VARCHAR(60),
    UF CHAR(2),
    CEP VARCHAR(8),
    DDD CHAR(4),
    TELEFONE VARCHAR(20),
    FAX VARCHAR(20),
    ENDERECO_ELETRONICO VARCHAR(255),
    REPRESENTANTE VARCHAR(50),
    CARGO_REPRESENTANTE VARCHAR(80),
    REGIAO_DE_COMERCIALIZACAO VARCHAR(1),
    DATA_REGISTRO_ANS DATE
);

-- Populando tabela com dados do arquivo Relatorio_cadop
LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 5.7\\Uploads\\Relatorio_cadop.csv'
INTO TABLE OPERADORAS_ATIVAS
CHARACTER SET UTF8 -- especifica o conjunto de caracteres
FIELDS TERMINATED BY ';' -- define o separador/delimitador dos campos
OPTIONALLY ENCLOSED BY '"' -- indica que alguns valores podem estar entre aspas
LINES TERMINATED BY '\n' -- define que o delimiteador de linha sera a quebra de linha
IGNORE 1 LINES -- ignora a primeira linha do arquivo contendo o nome dos campos
(REGISTRO_ANS, CNPJ , RAZAO_SOCIAL, NOME_FANTASIA, MODALIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, UF, 
CEP, DDD, TELEFONE, FAX, ENDERECO_ELETRONICO, REPRESENTANTE, CARGO_REPRESENTANTE, REGIAO_DE_COMERCIALIZACAO, DATA_REGISTRO_ANS);

SELECT REGISTRO_ANS FROM OPERADORAS_ATIVAS;

SELECT O.REGISTRO_ANS, O.CNPJ, O.RAZAO_SOCIAL, O.NOME_FANTASIA, O.MODALIDADE 
FROM OPERADORAS_ATIVAS O
WHERE NOME_FANTASIA LIKE "UNIMED%"
ORDER BY NOME_FANTASIA DESC
LIMIT 10;

-- Criando tabela de demonstrativos para o 1° trimestre
CREATE TABLE DEMONSTRATIVOS_TRIMESTRE_1 (
    ID SERIAL PRIMARY KEY,
    DATA_DEMONSTRATIVO DATE,
    REGISTRO_ANS BIGINT(6),
    CD_CONTA_CONTABIL VARCHAR(50),
    DESCRICAO VARCHAR(200),
    VL_SALDO_INICIAL DECIMAL(18,2),
    VL_SALDO_FINAL DECIMAL(18,2),
    FOREIGN KEY (REGISTRO_ANS) REFERENCES OPERADORAS_ATIVAS(REGISTRO_ANS)
);

-- Criando tabela de demonstrativos para o 2° trimestre
CREATE TABLE DEMONSTRATIVOS_TRIMESTRE_2 (
    ID SERIAL PRIMARY KEY,
    DATA_DEMONSTRATIVO DATE,
    REGISTRO_ANS BIGINT(6),
    CD_CONTA_CONTABIL VARCHAR(50),
    DESCRICAO VARCHAR(200),
    VL_SALDO_INICIAL DECIMAL(18,2),
    VL_SALDO_FINAL DECIMAL(18,2),
    FOREIGN KEY (REGISTRO_ANS) REFERENCES OPERADORAS_ATIVAS(REGISTRO_ANS)
);

-- Criando tabela de demonstrativos para o 3° trimestre
CREATE TABLE DEMONSTRATIVOS_TRIMESTRE_3 (
    ID SERIAL PRIMARY KEY,
    DATA_DEMONSTRATIVO DATE,
    REGISTRO_ANS BIGINT(6),
    CD_CONTA_CONTABIL VARCHAR(50),
    DESCRICAO VARCHAR(200),
    VL_SALDO_INICIAL DECIMAL(18,2),
    VL_SALDO_FINAL DECIMAL(18,2),
    FOREIGN KEY (REGISTRO_ANS) REFERENCES OPERADORAS_ATIVAS(REGISTRO_ANS)
);

-- Criando tabela de demonstrativos para o 4° trimestre
CREATE TABLE DEMONSTRATIVOS_TRIMESTRE_4 (
    ID SERIAL PRIMARY KEY,
    DATA_DEMONSTRATIVO DATE,
    REGISTRO_ANS BIGINT(6),
    CD_CONTA_CONTABIL VARCHAR(50),
    DESCRICAO VARCHAR(200),
    VL_SALDO_INICIAL DECIMAL(18,2),
    VL_SALDO_FINAL DECIMAL(18,2),
    FOREIGN KEY (REGISTRO_ANS) REFERENCES OPERADORAS_ATIVAS(REGISTRO_ANS)
);

-- Populando tabela com dados do arquivo 1_trimestre>2024
LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 5.7\\Uploads\\1_trimestre_2024.csv'
INTO TABLE DEMONSTRATIVOS_TRIMESTRE_1
CHARACTER SET UTF8
FIELDS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DATA_DEMONSTRATIVO, REGISTRO_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET 
    VL_SALDO_INICIAL = REPLACE(@VL_SALDO_INICIAL, ',', '.'), -- trocando a virgula pelo ponto por conta do formato do campo DECIMAL
    VL_SALDO_FINAL = REPLACE(@VL_SALDO_FINAL, ',', '.'); -- trocando a virgula pelo ponto por conta do formato do campo DECIMAL
    
-- Populando tabela com dados do arquivo 2_trimestre_2024
LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 5.7\\Uploads\\2_trimestre_2024.csv'
INTO TABLE DEMONSTRATIVOS_TRIMESTRE_2
CHARACTER SET UTF8
FIELDS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DATA_DEMONSTRATIVO, REGISTRO_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET 
    VL_SALDO_INICIAL = REPLACE(@VL_SALDO_INICIAL, ',', '.'),
    VL_SALDO_FINAL = REPLACE(@VL_SALDO_FINAL, ',', '.');
    
-- Populando tabela com dados do arquivo 3_trimestre_2024
LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 5.7\\Uploads\\3_trimestre_2024.csv'
INTO TABLE DEMONSTRATIVOS_TRIMESTRE_3
CHARACTER SET UTF8
FIELDS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DATA_DEMONSTRATIVO, REGISTRO_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET 
    VL_SALDO_INICIAL = REPLACE(@VL_SALDO_INICIAL, ',', '.'),
    VL_SALDO_FINAL = REPLACE(@VL_SALDO_FINAL, ',', '.');
    
-- Populando tabela com dados do arquivo 4_trimestre_2024
LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 5.7\\Uploads\\4_trimestre_2024.csv'
INTO TABLE DEMONSTRATIVOS_TRIMESTRE_4
CHARACTER SET UTF8
FIELDS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DATA_DEMONSTRATIVO, REGISTRO_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET 
    VL_SALDO_INICIAL = REPLACE(@VL_SALDO_INICIAL, ',', '.'),
    VL_SALDO_FINAL = REPLACE(@VL_SALDO_FINAL, ',', '.');
    

SELECT DESCRICAO FROM DEMONSTRATIVOS_TRIMESTRE_4 WHERE REGISTRO_ANS = 416398;

/* 3 - QUERIES ANALITICAS */
SELECT O.RAZAO_SOCIAL, SUM(D.VL_SALDO_FINAL) TOTAL_DESPESAS, D.DESCRICAO
FROM DEMONSTRATIVOS_TRIMESTRE_4 D
INNER JOIN OPERADORAS_ATIVAS O ON D.REGISTRO_ANS = O.REGISTRO_ANS
WHERE D.DESCRICAO = "EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR "
GROUP BY O.RAZAO_SOCIAL
HAVING TOTAL_DESPESAS > 0
ORDER BY TOTAL_DESPESAS DESC
LIMIT 10;

SELECT O.RAZAO_SOCIAL, SUM(D.VL_SALDO_FINAL) AS TOTAL_DESPESAS
FROM (
    SELECT REGISTRO_ANS, VL_SALDO_FINAL, DATA_DEMONSTRATIVO FROM DEMONSTRATIVOS_TRIMESTRE_1 -- unindo as tabelas de cada trimestre - 4 trimestre = 1 ano
    UNION ALL
    SELECT REGISTRO_ANS, VL_SALDO_FINAL, DATA_DEMONSTRATIVO FROM DEMONSTRATIVOS_TRIMESTRE_2
    UNION ALL
    SELECT REGISTRO_ANS, VL_SALDO_FINAL, DATA_DEMONSTRATIVO FROM DEMONSTRATIVOS_TRIMESTRE_3
    UNION ALL
    SELECT REGISTRO_ANS, VL_SALDO_FINAL, DATA_DEMONSTRATIVO FROM DEMONSTRATIVOS_TRIMESTRE_4
) D
INNER JOIN OPERADORAS_ATIVAS O ON D.REGISTRO_ANS = O.REGISTRO_ANS
WHERE D.DATA_DEMONSTRATIVO BETWEEN CURDATE() - INTERVAL 1 YEAR AND CURDATE() -- filtrando pelo último ano
GROUP BY O.RAZAO_SOCIAL -- agrupando pela razao social
ORDER BY TOTAL_DESPESAS DESC
LIMIT 10;
